Creating4Cut/Creating4Cut/urls.py
from django.contrib import admin
from django.urls import path
from app import views

###사진 업로드를 위한 코드 추가###
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('create', views.create, name='create'),
    path('detail/<int:post_pk>', views.detail, name='detail'),
] +static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

Creating4Cut/app/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title=models.CharField(max_length=200)
    content=models.TextField()

    def __str__(self):
        return self.title

class Photo(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    image=models.ImageField(upload_to='images/', blank=True, null=True)

Creating4Cut/app/views.py
from django.shortcuts import render, redirect
from .models import Post, Photo
from datetime import timezone
# Create your views here.

def create(request):
    if(request.method == 'POST'):

        new_post= Post.objects.create(
            title = request.POST['title'],
            content = request.POST['content']
        )


        #name속성이 imgs인 input 태그로부터 받은 파일들을 반복문을 통해 하나씩 가져온다
        for img in request.FILES.getlist('imgs'):
            #Photo 객체를 하나 생성한다.
            photo=Photo()
            #외래키로 현재 생성한 Post의 기본키를 참조한다.
            photo.post = new_post
            #imgs로 부터 가져온 이미지 파일 하나를 저장한다.
            photo.image = img
            #데이터베이스에 저장
            photo.save()

        return redirect('detail',new_post.pk)
    return render(request, 'create.html' )

def detail(request, post_pk):
    post=Post.objects.get(pk=post_pk)
    return render(request, 'detail.html', {'post':post})

Creating4Cut/app/templates/create.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Creating4Cut</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '../static/create.css' %}"
</head>
<body>
    <div class="container">
        <div class="photos">
            <div class="photo-frame">
                <form method="POST" action="{% url 'create' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="title">제목:</label>
                    <input type="text" name="title" id="title"><br>
                    <label for="content">내용:</label>
                    <input type="text" name="content">
                    <input type="file" name="imgs" multiple>
                    <input type="submit" value="작성하기">
                </form>

                </form>
            </div>
        </div>
    </div>
</body>
</html>

Creating4Cut/app/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>

<script type="text/javascript">

$(document).ready(function(){

$("#copy").on("click",function(){

html2canvas($('#copy_div')[0]).then(function(canvas){

var img = document.createElement("a");

img.download = "test.png";

img.href=canvas.toDataURL();

document.body.appendChild(img);

img.click();

});

});

});

</script>
</head>

<body>
    <div class="container">
        <div class="photos" class="copy_div" id="copy_div">
            {% for photo in post.photo_set.all %}
                <img class="photo-frame" src="{{photo.image.url}}" height="200"><br>
            {% endfor %}
        </div>
        <button type="button" id="copy">복사</button>
        <a href="{% url 'create' %}">새로 만들기</a>
    </div>
</body>
</html>